# Email credentials
EMAIL = "<YOURGOOGLEEMAIL>@gmail.com"
EMAIL_APP_PASSWORD = "<YOUR GOOGLE APP PASSWORD>"  # APP Password
IMAP_SERVER = "imap.gmail.com"  # For Gmail. Use your provider's IMAP server.
TEST_EMAIL_ALERTS = True
EMAIL_ALERT_SUBJECTS=["vto", "vet"]

# Notify Me/Voice Monkey
NOTIFICATIONS_TOKEN='amzn1.ask.account.AGNSD33RSAREVXQMXT5PVEZDCYRPHMYX6VCDA4ZWU76YQFTR5ZM6EEDT3V3GSJPFWUVGRRGJYP5PTMQWKUH6S6TCS3EEN4IGDQ6DY'
VOICEMONKEY_TOKEN="8c98ca_0ba1d9eb0000000000000326ed9"
VOICEMONKEY_DEVICE="my-echo-plus"


